# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
  service: S3
  access_key_id: AKIA2LB6STMF4HHOJZ5E
  secret_access_key: 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
  region: us-west-1
  bucket: petshappy2